# Generated by Django 5.1 on 2024-09-20 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='baseuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='account.baseuser'),
        ),
    ]
