# Generated by Django 5.1 on 2024-09-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_subscription_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='profileAvtar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='img/profile_img/')),
            ],
        ),
    ]
