# Generated by Django 5.1 on 2024-09-21 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_actor_genres_profile_choices_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genres',
            new_name='Genre',
        ),
    ]
