# Generated by Django 5.1 on 2024-09-21 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_rename_genres_genre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile_Choices',
            new_name='Profile_Choice',
        ),
    ]
