# Generated by Django 5.1 on 2024-09-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_rename_profile_choices_profile_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='no_of_profile',
            field=models.IntegerField(default=0),
        ),
    ]
