# Generated by Django 5.1 on 2024-09-21 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_remove_profile_id_profile_profile_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ['name']},
        ),
    ]
