# Generated by Django 5.1 on 2024-09-21 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_actor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
    ]
