# Generated by Django 5.1 on 2024-09-23 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_genre_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='account.profile_choice'),
        ),
    ]
