# Generated by Django 5.1 on 2024-09-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_content_profile_content_list_profile_content_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='c_id',
            field=models.CharField(default=1,blank=True, max_length=50, null=True),
        ),
    ]
