# Generated by Django 5.1 on 2024-09-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_content_c_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='c_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
