# Generated by Django 5.1 on 2024-09-27 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_content_c_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_content_list',
            name='content',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='content_list',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='Profile_Content_List',
        ),
    ]
