# Generated by Django 5.1 on 2024-09-27 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_content_profile_content_list_profile_content_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_content_list',
            name='content',
        ),
        migrations.AddField(
            model_name='profile_content_list',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.content', unique=True),
        ),
    ]
