# Generated by Django 5.1 on 2024-09-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_remove_profile_content_list_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='c_id',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='profile_content_list',
            name='content',
        ),
        migrations.AddField(
            model_name='profile_content_list',
            name='content',
            field=models.ManyToManyField(to='account.content'),
        ),
    ]
