# Generated by Django 5.1 on 2024-09-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_alter_content_c_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_content_list',
            name='content',
        ),
        migrations.AddField(
            model_name='profile_content_list',
            name='Movies',
            field=models.ManyToManyField(related_name='movie', to='account.content'),
        ),
        migrations.AddField(
            model_name='profile_content_list',
            name='Seasons',
            field=models.ManyToManyField(related_name='season', to='account.content'),
        ),
        migrations.AlterField(
            model_name='content',
            name='c_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
