# Generated by Django 5.1 on 2024-09-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_remove_profile_content_list_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='c_id',
            field=models.IntegerField(default=1),
        ),
    ]
