# Generated by Django 5.1 on 2024-09-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_alter_content_c_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_content_list',
            name='Movies',
        ),
        migrations.RemoveField(
            model_name='profile_content_list',
            name='Seasons',
        ),
        migrations.AddField(
            model_name='profile_content_list',
            name='content',
            field=models.ManyToManyField(to='account.content'),
        ),
    ]
