# Generated by Django 5.1 on 2024-09-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_remove_profile_content_list_movies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='c_id',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
