# Generated by Django 5.1 on 2024-09-27 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_alter_content_c_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='content_list',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_list', to='account.profile_content_list'),
        ),
    ]
