# Generated by Django 5.1 on 2024-09-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_alter_profile_content_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_content_list',
            name='content',
        ),
        migrations.AddField(
            model_name='profile_content_list',
            name='movies',
            field=models.ManyToManyField(related_name='movies', to='account.content'),
        ),
        migrations.AddField(
            model_name='profile_content_list',
            name='seasons',
            field=models.ManyToManyField(related_name='seasons', to='account.content'),
        ),
    ]
