# Generated by Django 5.1 on 2024-09-29 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_remove_profile_content_list_movies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_Liked_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ManyToManyField(to='account.content')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='liked_content',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.profile_liked_list'),
        ),
    ]
