# Generated by Django 5.1.2 on 2024-10-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_alter_actor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
