# Generated by Django 5.1.2 on 2024-10-14 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_baseuser_token_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseuser',
            old_name='token_created_at',
            new_name='token_expiry_at',
        ),
    ]
