# Generated by Django 5.1 on 2024-09-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_profile_choice'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='genres',
        ),
        migrations.AddField(
            model_name='series',
            name='genres',
            field=models.ManyToManyField(to='account.genre'),
        ),
    ]
