# Generated by Django 5.1 on 2024-09-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_season_genres_series_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='thumbnail',
            field=models.CharField(max_length=350),
        ),
    ]
