# Generated by Django 5.1 on 2024-09-24 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_episode_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='upload_episode',
            new_name='episode',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='upload_trailer',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='upload_movie',
            new_name='trailer',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='upload_trailer',
            new_name='trailer',
        ),
    ]
