# Generated by Django 5.1 on 2024-09-25 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_rename_upload_episode_episode_episode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episode', to='content.series'),
        ),
    ]
