# Generated by Django 5.1 on 2024-09-25 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_episode_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='series',
        ),
    ]
