# Generated by Django 5.1 on 2024-09-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_episode_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
