# Generated by Django 5.1 on 2024-09-27 19:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_season_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=True),
        ),
       
    ]
