# Generated by Django 5.1 on 2024-09-27 19:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_alter_season_season_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
 
        
    ]
