# Generated by Django 5.1 on 2024-09-27 19:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_alter_movie_movie_uid_alter_season_season_uid'),
    ]

    operations = [
      
    ]
