# Generated by Django 5.1 on 2024-09-27 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_alter_season_season_uid'),
    ]

    operations = [
        
    ]
