# Generated by Django 5.1 on 2024-09-27 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_season_season_uid'),
    ]

    operations = [
        
    ]
