# Generated by Django 5.1 on 2024-09-27 19:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_remove_season_season_uid'),
    ]

    operations = [
      
    ]
