# Generated by Django 5.1 on 2024-09-27 19:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_alter_season_season_uid'),
    ]

    operations = [
      
        
    ]
