# Generated by Django 5.1 on 2024-09-27 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_alter_season_season_uid'),
    ]

    operations = [
    
    ]
