# Generated by Django 5.1 on 2024-09-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_rename_season_uid_season_season_id'),
    ]

    operations = [
      
        
    ]
