# Generated by Django 5.1 on 2024-09-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_remove_season_season_id_season_id'),
    ]

    operations = [
        
    ]
