# Generated by Django 5.1 on 2024-09-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_season_season_uid'),
    ]

    operations = [
       
    ]
