# Generated by Django 5.1 on 2024-09-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_remove_season_season_uid_alter_season_id'),
    ]

    operations = [
       
    ]
