# Generated by Django 5.1 on 2024-09-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_season_shaligram_alter_season_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='shaligram',
            field=models.CharField(default='SHIV', max_length=150),
            preserve_default=False,
        ),
    ]
