# Generated by Django 5.1 on 2024-09-27 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_season_shaligram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='shaligram',
        ),
    ]
