# Generated by Django 5.1 on 2024-09-27 20:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_remove_season_shaligram'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='season_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
