# Generated by Django 5.1 on 2024-09-27 20:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_season_season_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='season_id',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
