# Generated by Django 5.1 on 2024-10-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_profile_liked_list_profile_liked_content'),
        ('content', '0030_alter_season_season_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='actors',
            field=models.ManyToManyField(related_name='season', to='account.actor'),
        ),
    ]
