# Generated by Django 5.1 on 2024-10-08 09:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0034_alter_movie_movie_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_uid',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
